### ISSUE TITLE
Question: Any known side effects?

### ISSUE THREAD

**Issue by kapsiR** [kellwinr/galaxybook_mask#5]
First of all, thanks for the hint to these two registry keys. 🙏

Do you know if there are any known side effects when the BIOS manufacturer and product info changes?

Thanks!

**Comment by rzfzr** [comment]
From my understanding, the direct launch method found in the releases, should be pretty safe and only interfere on something if that something happens to check on those values between the execution and the timeout in the .bat. This is because it restores those two values before closing.

**Comment by kellwinr** [comment]
> First of all, thanks for the hint to these two registry keys. 🙏
> 
> Do you know if there are any known side effects when the BIOS manufacturer and product info changes?
> 
> Thanks!

No, because the registry itself doesn't keep the changed keys after you reboot, it reverts back after you reboot your laptop. Thats why there's is also a startup version to run the command to edit the 2 keys every time you reboot; you can undo the changes easily if you use the one with startup by just simply locating the startup batch file.

**Comment by kapsiR** [comment]
Thanks for the answer and your time! 

> No, because the registry itself doesn't keep the changed keys after you reboot, it reverts back after you reboot your laptop. 

Yes, I verified this behavior.  
I think I'd have to monitor any queries on this specific keys to get a rough overview what parts of the system depend on it...

But for now, I'll stick with "probably no side effects" 😊
