### ISSUE TITLE
Any possibility to make it work with the "Samsung Settings" app?

### ISSUE THREAD

**Issue by haraop** [kellwinr/galaxybook_mask#7]
I'm trying to make  the "Samsung Settings" app work with my non-samsung device. Although I'm stuck in a phase where is asking a "system events controller driver", which is easily found online on the 1.0.0.8 version, and even though I make sure it's installed, it's not working. You can see some threads about it here and here:

https://forum.xda-developers.com/t/samsung-multicontrol-with-non-samsung-device.4560313/
https://www.reddit.com/r/GalaxyBook/comments/10z6ddw/samsung_settings_app_for_windows_10/

**Comment by kellwinr** [comment]
Imo, it is kind of impossible to make it work since Samsung Settings is connected to a lot of **hardware-related** controls, such as the display, battery, processor, wireless drivers, etc. The remaining driver will not be compatible at all, and you will get _error=10_ by installing it manually. 
Even though if you managed to get the app running, the function in the app is less likely to work because of the wrong & incompatible hardware & drivers as it is developed by Samsung to run on set specific device models.

Samsung Settings is just like the MyASUS app & Lenovo Vantage app; all require specific devices and hardware to run. Other samsung applications like SamsungNotes and SamsungAccount are not connected to the actual hardware or drivers, so software modification is possible in this case.

**Comment by haraop** [comment]
@kellwinr Thank you for dedicating some time for the answer. Greatly appreciated.

**Comment by kellwinr** [comment]
@haraop a solution was created that will allow Samsung Settings to run but some features of course will not work (hw ones)
https://xdaforums.com/t/how-to-samsung-multi-control-with-non-samsung-windows-pc.4640205/
